### ISSUE TITLE
SlevomatCodingStandard.ControlStructures.EarlyExit modifies unrelated expression

### ISSUE THREAD

**Issue by morozov** [slevomat/coding-standard#1131]
```
$ composer show | grep -P 'coding-standard|php_codesniffer'
doctrine/coding-standard                       8.1.0   The Doctrine Coding Standard is a ...
slevomat/coding-standard                       6.3.10  Slevomat Coding Standard for PHP_C...
squizlabs/php_codesniffer                      3.5.8   PHP_CodeSniffer tokenizes PHP, Jav...
```
Consider the following code example:
```php
<?php

declare(strict_types=1);

function foo(bool $flag): bool
{
    return $flag;
}

function bar(int $a, int $b): void
{
    if ($a !== $b && foo($a !== $b)) {
        var_dump(1);
    }
}
```
Try fixing the file automatically:
```
phpcbf test.php
F 1 / 1 (100%)

PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
test.php                                              1      2
----------------------------------------------------------------------
```
Note the resulting content:
```php
<?php

declare(strict_types=1);

function foo(bool $flag): bool
{
    return $flag;
}

function bar(int $a, int $b): void
{
    if ($a === $b || foo($a === $b)) {
        return;
    }

    var_dump(1);
}
```
Instead of being called with the value of `$a !== $b`, `foo()` is now called with the value of `$a === $b`.

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/e1929b4c7f6380f50ca192d5b8e8e5a13973865e

**Comment by morozov** [comment]
Thanks for the fix, @kukulich. Unfortunately, it's still happening under similar circumstances:
```php
<?php

declare(strict_types=1);

function foo(bool $flag): bool
{
    return $flag;
}

function bar(int $a, int $b, bool $c): void
{
    if ($a !== $b && $c == foo($a !== $b)) {
        var_dump(1);
    }
}
```
The above gets transformed to:
```php
<?php

declare(strict_types=1);

function foo(bool $flag): bool
{
    return $flag;
}

function bar(int $a, int $b, bool $c): void
{
    if ($a === $b || $c != foo($a === $b)) {
        return;
    }

    var_dump(1);
}
```

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/8093b16b17f469ca5ece81fcd59688ab08221df3

**Comment by morozov** [comment]
https://github.com/slevomat/coding-standard/blob/8093b16b17f469ca5ece81fcd59688ab08221df3/SlevomatCodingStandard/Helpers/ConditionHelper.php#L239

Looking at the code change above, I think there are more cases (most of which are exotic) that can be impacted by this sniff:
```php
<?php

function bar(int $a, int $b, array $c, array $d): void
{
    if ($c[$a !== $b] && $d{$a !== $b} && print $a !== $b) {
        var_dump(1);
    }
}
```
I realize that the sniff operates on a token stream, not on an AST, so addressing the `print` case may be challenging, and the case itself may be pointless. So, it's just a heads up.

Thank you @kukulich for your hard work on fixing these edge cases.
