### ISSUE TITLE
EarlyExitSniff crashing

### ISSUE THREAD

**Issue by paranoiq** [slevomat/coding-standard#345]
fails on file:
```
<?php declare(strict_types = 1);

use Tracy\Debugger;

require_once __DIR__ . '/../../vendor/autoload.php';
require_once __DIR__ . '/../../vendor/nette/tester/Tester/bootstrap.php';

if (!empty($_SERVER['argv'])) {
    // may be running from command line, but under 'cgi-fcgi' SAPI
    header('Content-Type: text/plain');
} elseif (PHP_SAPI !== 'cli') {
    // running from browser
    Debugger::enable(Debugger::DEVELOPMENT, dirname(dirname(__DIR__)) . '/logs/');
}
```
with output:
```
FILE: C:\http\paranoiq\dogma\tests\Dogma\bootstrap.php
-------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------
 1 | ERROR | An error occurred during processing; checking has been aborted. The error message was:
   |       | Undefined index:  in
   |       | C:\http\paranoiq\dogma\vendor\slevomat\coding-standard\SlevomatCodingStandard\Sniffs\ControlStructures\EarlyExitSniff.php
   |       | on line 482 (Internal.Exception)
-------------------------------------------------------------------------------------------------------
```

**Comment by kukulich** [comment]
@paranoiq Can you try `dev-master` please? I think I fixed this already.

**Comment by paranoiq** [comment]
@kukulich nope. still fails with `slevomat/coding-standard (dev-master 2b5a5a2)`

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/9cefbf1067b580c3878f5202a2b4e234f0a71b3f
